# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/spinzed/Workspaces/faks/zavrsni-kod

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/spinzed/Workspaces/faks/zavrsni-kod

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"assimp-dev\" \"libassimp5.4.1-dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/spinzed/Workspaces/faks/zavrsni-kod/CMakeFiles /home/spinzed/Workspaces/faks/zavrsni-kod//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/spinzed/Workspaces/faks/zavrsni-kod/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rt-renderer

# Build rule for target.
rt-renderer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rt-renderer
.PHONY : rt-renderer

# fast build rule for target.
rt-renderer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/build
.PHONY : rt-renderer/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f dependencies/glfw/CMakeFiles/uninstall.dir/build.make dependencies/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f dependencies/glfw/src/CMakeFiles/glfw.dir/build.make dependencies/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f dependencies/glfw/src/CMakeFiles/update_mappings.dir/build.make dependencies/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named assimp

# Build rule for target.
assimp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 assimp
.PHONY : assimp

# fast build rule for target.
assimp/fast:
	$(MAKE) $(MAKESILENT) -f dependencies/assimp/code/CMakeFiles/assimp.dir/build.make dependencies/assimp/code/CMakeFiles/assimp.dir/build
.PHONY : assimp/fast

dependencies/glad/src/glad.o: dependencies/glad/src/glad.c.o
.PHONY : dependencies/glad/src/glad.o

# target to build an object file
dependencies/glad/src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/dependencies/glad/src/glad.c.o
.PHONY : dependencies/glad/src/glad.c.o

dependencies/glad/src/glad.i: dependencies/glad/src/glad.c.i
.PHONY : dependencies/glad/src/glad.i

# target to preprocess a source file
dependencies/glad/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/dependencies/glad/src/glad.c.i
.PHONY : dependencies/glad/src/glad.c.i

dependencies/glad/src/glad.s: dependencies/glad/src/glad.c.s
.PHONY : dependencies/glad/src/glad.s

# target to generate assembly for a file
dependencies/glad/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/dependencies/glad/src/glad.c.s
.PHONY : dependencies/glad/src/glad.c.s

sources/Animation.o: sources/Animation.cpp.o
.PHONY : sources/Animation.o

# target to build an object file
sources/Animation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Animation.cpp.o
.PHONY : sources/Animation.cpp.o

sources/Animation.i: sources/Animation.cpp.i
.PHONY : sources/Animation.i

# target to preprocess a source file
sources/Animation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Animation.cpp.i
.PHONY : sources/Animation.cpp.i

sources/Animation.s: sources/Animation.cpp.s
.PHONY : sources/Animation.s

# target to generate assembly for a file
sources/Animation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Animation.cpp.s
.PHONY : sources/Animation.cpp.s

sources/Animator.o: sources/Animator.cpp.o
.PHONY : sources/Animator.o

# target to build an object file
sources/Animator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Animator.cpp.o
.PHONY : sources/Animator.cpp.o

sources/Animator.i: sources/Animator.cpp.i
.PHONY : sources/Animator.i

# target to preprocess a source file
sources/Animator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Animator.cpp.i
.PHONY : sources/Animator.cpp.i

sources/Animator.s: sources/Animator.cpp.s
.PHONY : sources/Animator.s

# target to generate assembly for a file
sources/Animator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Animator.cpp.s
.PHONY : sources/Animator.cpp.s

sources/Camera.o: sources/Camera.cpp.o
.PHONY : sources/Camera.o

# target to build an object file
sources/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Camera.cpp.o
.PHONY : sources/Camera.cpp.o

sources/Camera.i: sources/Camera.cpp.i
.PHONY : sources/Camera.i

# target to preprocess a source file
sources/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Camera.cpp.i
.PHONY : sources/Camera.cpp.i

sources/Camera.s: sources/Camera.cpp.s
.PHONY : sources/Camera.s

# target to generate assembly for a file
sources/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Camera.cpp.s
.PHONY : sources/Camera.cpp.s

sources/Cube.o: sources/Cube.cpp.o
.PHONY : sources/Cube.o

# target to build an object file
sources/Cube.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Cube.cpp.o
.PHONY : sources/Cube.cpp.o

sources/Cube.i: sources/Cube.cpp.i
.PHONY : sources/Cube.i

# target to preprocess a source file
sources/Cube.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Cube.cpp.i
.PHONY : sources/Cube.cpp.i

sources/Cube.s: sources/Cube.cpp.s
.PHONY : sources/Cube.s

# target to generate assembly for a file
sources/Cube.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Cube.cpp.s
.PHONY : sources/Cube.cpp.s

sources/Curve.o: sources/Curve.cpp.o
.PHONY : sources/Curve.o

# target to build an object file
sources/Curve.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Curve.cpp.o
.PHONY : sources/Curve.cpp.o

sources/Curve.i: sources/Curve.cpp.i
.PHONY : sources/Curve.i

# target to preprocess a source file
sources/Curve.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Curve.cpp.i
.PHONY : sources/Curve.cpp.i

sources/Curve.s: sources/Curve.cpp.s
.PHONY : sources/Curve.s

# target to generate assembly for a file
sources/Curve.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Curve.cpp.s
.PHONY : sources/Curve.cpp.s

sources/Framebuffer.o: sources/Framebuffer.cpp.o
.PHONY : sources/Framebuffer.o

# target to build an object file
sources/Framebuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Framebuffer.cpp.o
.PHONY : sources/Framebuffer.cpp.o

sources/Framebuffer.i: sources/Framebuffer.cpp.i
.PHONY : sources/Framebuffer.i

# target to preprocess a source file
sources/Framebuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Framebuffer.cpp.i
.PHONY : sources/Framebuffer.cpp.i

sources/Framebuffer.s: sources/Framebuffer.cpp.s
.PHONY : sources/Framebuffer.s

# target to generate assembly for a file
sources/Framebuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Framebuffer.cpp.s
.PHONY : sources/Framebuffer.cpp.s

sources/Importer.o: sources/Importer.cpp.o
.PHONY : sources/Importer.o

# target to build an object file
sources/Importer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Importer.cpp.o
.PHONY : sources/Importer.cpp.o

sources/Importer.i: sources/Importer.cpp.i
.PHONY : sources/Importer.i

# target to preprocess a source file
sources/Importer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Importer.cpp.i
.PHONY : sources/Importer.cpp.i

sources/Importer.s: sources/Importer.cpp.s
.PHONY : sources/Importer.s

# target to generate assembly for a file
sources/Importer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Importer.cpp.s
.PHONY : sources/Importer.cpp.s

sources/Mesh.o: sources/Mesh.cpp.o
.PHONY : sources/Mesh.o

# target to build an object file
sources/Mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Mesh.cpp.o
.PHONY : sources/Mesh.cpp.o

sources/Mesh.i: sources/Mesh.cpp.i
.PHONY : sources/Mesh.i

# target to preprocess a source file
sources/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Mesh.cpp.i
.PHONY : sources/Mesh.cpp.i

sources/Mesh.s: sources/Mesh.cpp.s
.PHONY : sources/Mesh.s

# target to generate assembly for a file
sources/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Mesh.cpp.s
.PHONY : sources/Mesh.cpp.s

sources/Object.o: sources/Object.cpp.o
.PHONY : sources/Object.o

# target to build an object file
sources/Object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Object.cpp.o
.PHONY : sources/Object.cpp.o

sources/Object.i: sources/Object.cpp.i
.PHONY : sources/Object.i

# target to preprocess a source file
sources/Object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Object.cpp.i
.PHONY : sources/Object.cpp.i

sources/Object.s: sources/Object.cpp.s
.PHONY : sources/Object.s

# target to generate assembly for a file
sources/Object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Object.cpp.s
.PHONY : sources/Object.cpp.s

sources/Renderer.o: sources/Renderer.cpp.o
.PHONY : sources/Renderer.o

# target to build an object file
sources/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Renderer.cpp.o
.PHONY : sources/Renderer.cpp.o

sources/Renderer.i: sources/Renderer.cpp.i
.PHONY : sources/Renderer.i

# target to preprocess a source file
sources/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Renderer.cpp.i
.PHONY : sources/Renderer.cpp.i

sources/Renderer.s: sources/Renderer.cpp.s
.PHONY : sources/Renderer.s

# target to generate assembly for a file
sources/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Renderer.cpp.s
.PHONY : sources/Renderer.cpp.s

sources/Shader.o: sources/Shader.cpp.o
.PHONY : sources/Shader.o

# target to build an object file
sources/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Shader.cpp.o
.PHONY : sources/Shader.cpp.o

sources/Shader.i: sources/Shader.cpp.i
.PHONY : sources/Shader.i

# target to preprocess a source file
sources/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Shader.cpp.i
.PHONY : sources/Shader.cpp.i

sources/Shader.s: sources/Shader.cpp.s
.PHONY : sources/Shader.s

# target to generate assembly for a file
sources/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Shader.cpp.s
.PHONY : sources/Shader.cpp.s

sources/Sphere.o: sources/Sphere.cpp.o
.PHONY : sources/Sphere.o

# target to build an object file
sources/Sphere.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Sphere.cpp.o
.PHONY : sources/Sphere.cpp.o

sources/Sphere.i: sources/Sphere.cpp.i
.PHONY : sources/Sphere.i

# target to preprocess a source file
sources/Sphere.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Sphere.cpp.i
.PHONY : sources/Sphere.cpp.i

sources/Sphere.s: sources/Sphere.cpp.s
.PHONY : sources/Sphere.s

# target to generate assembly for a file
sources/Sphere.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Sphere.cpp.s
.PHONY : sources/Sphere.cpp.s

sources/Texture.o: sources/Texture.cpp.o
.PHONY : sources/Texture.o

# target to build an object file
sources/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Texture.cpp.o
.PHONY : sources/Texture.cpp.o

sources/Texture.i: sources/Texture.cpp.i
.PHONY : sources/Texture.i

# target to preprocess a source file
sources/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Texture.cpp.i
.PHONY : sources/Texture.cpp.i

sources/Texture.s: sources/Texture.cpp.s
.PHONY : sources/Texture.s

# target to generate assembly for a file
sources/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Texture.cpp.s
.PHONY : sources/Texture.cpp.s

sources/TextureObject.o: sources/TextureObject.cpp.o
.PHONY : sources/TextureObject.o

# target to build an object file
sources/TextureObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/TextureObject.cpp.o
.PHONY : sources/TextureObject.cpp.o

sources/TextureObject.i: sources/TextureObject.cpp.i
.PHONY : sources/TextureObject.i

# target to preprocess a source file
sources/TextureObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/TextureObject.cpp.i
.PHONY : sources/TextureObject.cpp.i

sources/TextureObject.s: sources/TextureObject.cpp.s
.PHONY : sources/TextureObject.s

# target to generate assembly for a file
sources/TextureObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/TextureObject.cpp.s
.PHONY : sources/TextureObject.cpp.s

sources/ThreadPool.o: sources/ThreadPool.cpp.o
.PHONY : sources/ThreadPool.o

# target to build an object file
sources/ThreadPool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/ThreadPool.cpp.o
.PHONY : sources/ThreadPool.cpp.o

sources/ThreadPool.i: sources/ThreadPool.cpp.i
.PHONY : sources/ThreadPool.i

# target to preprocess a source file
sources/ThreadPool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/ThreadPool.cpp.i
.PHONY : sources/ThreadPool.cpp.i

sources/ThreadPool.s: sources/ThreadPool.cpp.s
.PHONY : sources/ThreadPool.s

# target to generate assembly for a file
sources/ThreadPool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/ThreadPool.cpp.s
.PHONY : sources/ThreadPool.cpp.s

sources/Timer.o: sources/Timer.cpp.o
.PHONY : sources/Timer.o

# target to build an object file
sources/Timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Timer.cpp.o
.PHONY : sources/Timer.cpp.o

sources/Timer.i: sources/Timer.cpp.i
.PHONY : sources/Timer.i

# target to preprocess a source file
sources/Timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Timer.cpp.i
.PHONY : sources/Timer.cpp.i

sources/Timer.s: sources/Timer.cpp.s
.PHONY : sources/Timer.s

# target to generate assembly for a file
sources/Timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Timer.cpp.s
.PHONY : sources/Timer.cpp.s

sources/Transform.o: sources/Transform.cpp.o
.PHONY : sources/Transform.o

# target to build an object file
sources/Transform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Transform.cpp.o
.PHONY : sources/Transform.cpp.o

sources/Transform.i: sources/Transform.cpp.i
.PHONY : sources/Transform.i

# target to preprocess a source file
sources/Transform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Transform.cpp.i
.PHONY : sources/Transform.cpp.i

sources/Transform.s: sources/Transform.cpp.s
.PHONY : sources/Transform.s

# target to generate assembly for a file
sources/Transform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/Transform.cpp.s
.PHONY : sources/Transform.cpp.s

sources/WindowManager.o: sources/WindowManager.cpp.o
.PHONY : sources/WindowManager.o

# target to build an object file
sources/WindowManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/WindowManager.cpp.o
.PHONY : sources/WindowManager.cpp.o

sources/WindowManager.i: sources/WindowManager.cpp.i
.PHONY : sources/WindowManager.i

# target to preprocess a source file
sources/WindowManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/WindowManager.cpp.i
.PHONY : sources/WindowManager.cpp.i

sources/WindowManager.s: sources/WindowManager.cpp.s
.PHONY : sources/WindowManager.s

# target to generate assembly for a file
sources/WindowManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/WindowManager.cpp.s
.PHONY : sources/WindowManager.cpp.s

sources/main.o: sources/main.cpp.o
.PHONY : sources/main.o

# target to build an object file
sources/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/main.cpp.o
.PHONY : sources/main.cpp.o

sources/main.i: sources/main.cpp.i
.PHONY : sources/main.i

# target to preprocess a source file
sources/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/main.cpp.i
.PHONY : sources/main.cpp.i

sources/main.s: sources/main.cpp.s
.PHONY : sources/main.s

# target to generate assembly for a file
sources/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/main.cpp.s
.PHONY : sources/main.cpp.s

sources/mtr.o: sources/mtr.cpp.o
.PHONY : sources/mtr.o

# target to build an object file
sources/mtr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/mtr.cpp.o
.PHONY : sources/mtr.cpp.o

sources/mtr.i: sources/mtr.cpp.i
.PHONY : sources/mtr.i

# target to preprocess a source file
sources/mtr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/mtr.cpp.i
.PHONY : sources/mtr.cpp.i

sources/mtr.s: sources/mtr.cpp.s
.PHONY : sources/mtr.s

# target to generate assembly for a file
sources/mtr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rt-renderer.dir/build.make CMakeFiles/rt-renderer.dir/sources/mtr.cpp.s
.PHONY : sources/mtr.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... assimp"
	@echo "... glfw"
	@echo "... rt-renderer"
	@echo "... dependencies/glad/src/glad.o"
	@echo "... dependencies/glad/src/glad.i"
	@echo "... dependencies/glad/src/glad.s"
	@echo "... sources/Animation.o"
	@echo "... sources/Animation.i"
	@echo "... sources/Animation.s"
	@echo "... sources/Animator.o"
	@echo "... sources/Animator.i"
	@echo "... sources/Animator.s"
	@echo "... sources/Camera.o"
	@echo "... sources/Camera.i"
	@echo "... sources/Camera.s"
	@echo "... sources/Cube.o"
	@echo "... sources/Cube.i"
	@echo "... sources/Cube.s"
	@echo "... sources/Curve.o"
	@echo "... sources/Curve.i"
	@echo "... sources/Curve.s"
	@echo "... sources/Framebuffer.o"
	@echo "... sources/Framebuffer.i"
	@echo "... sources/Framebuffer.s"
	@echo "... sources/Importer.o"
	@echo "... sources/Importer.i"
	@echo "... sources/Importer.s"
	@echo "... sources/Mesh.o"
	@echo "... sources/Mesh.i"
	@echo "... sources/Mesh.s"
	@echo "... sources/Object.o"
	@echo "... sources/Object.i"
	@echo "... sources/Object.s"
	@echo "... sources/Renderer.o"
	@echo "... sources/Renderer.i"
	@echo "... sources/Renderer.s"
	@echo "... sources/Shader.o"
	@echo "... sources/Shader.i"
	@echo "... sources/Shader.s"
	@echo "... sources/Sphere.o"
	@echo "... sources/Sphere.i"
	@echo "... sources/Sphere.s"
	@echo "... sources/Texture.o"
	@echo "... sources/Texture.i"
	@echo "... sources/Texture.s"
	@echo "... sources/TextureObject.o"
	@echo "... sources/TextureObject.i"
	@echo "... sources/TextureObject.s"
	@echo "... sources/ThreadPool.o"
	@echo "... sources/ThreadPool.i"
	@echo "... sources/ThreadPool.s"
	@echo "... sources/Timer.o"
	@echo "... sources/Timer.i"
	@echo "... sources/Timer.s"
	@echo "... sources/Transform.o"
	@echo "... sources/Transform.i"
	@echo "... sources/Transform.s"
	@echo "... sources/WindowManager.o"
	@echo "... sources/WindowManager.i"
	@echo "... sources/WindowManager.s"
	@echo "... sources/main.o"
	@echo "... sources/main.i"
	@echo "... sources/main.s"
	@echo "... sources/mtr.o"
	@echo "... sources/mtr.i"
	@echo "... sources/mtr.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

